### ISSUE TITLE
filtering goes wrong with this subtitle.

### ISSUE THREAD

**Issue by hboetes** [mattlyon93/filter-subs#1]
Thanks for your awesome subtitle filter.

Here is an srt file this goes rather wrong. Would that be interesting to you?

```
1
00:00:03,542 --> 00:00:05,294
BARFOO:
Have you ever removed your thingiebob?

2
00:00:05,377 --> 00:00:06,378
THE FOOBAR: No.

3
00:00:06,462 --> 00:00:08,172
BARFOO:
Has it ever been removed by others?

4
00:00:08,255 --> 00:00:09,632
THE FOOBAR: Never.

5
00:00:09,715 --> 00:00:10,883
ARMORER: This is nonsense.

6
00:00:10,966 --> 00:00:12,426
FOOBAR GROUP: This is nonsense.
```

**Comment by mattlyon93** [comment]
> Thanks for your awesome subtitle filter.
No worries, thank you for the kind words!

> Would that be interesting to you?
Yes definitely, I will take a look at this tomorrow.

**Comment by mattlyon93** [comment]
Should be fixed now, and have released a new version. 👍

**Comment by hboetes** [comment]
Thanks, and congrats on fixing your first issue. =)
