### ISSUE TITLE
Why does filter-subs remove this item?

### ISSUE THREAD

**Issue by hboetes** [mattlyon93/filter-subs#10]
```
1
00:00:03,625 --> 00:00:07,125
foobar

```

I don't see what's wrong with it. And it gets deleted no matter what the contents of the subtitle text. It's a mystery to me.

**Comment by mattlyon93** [comment]
I cannot replicate the issue you are having just by copying and pasting the subtitle text into an `.srt` file. Are you using the latest version of `subtitle-filter`? Currently it is `v1.4.3`.
If the issue persists, are you able to upload a `.srt` file containing the problematic subtitle?
