### ISSUE TITLE
Another small problem.

### ISSUE THREAD

**Issue by hboetes** [mattlyon93/filter-subs#2]
Here is another small problem.

```
39
00:03:32,296 --> 00:03:34,840
FOO BAR 4: (IN ENGLISH)
Regular text.
```

**Comment by mattlyon93** [comment]
Yes, so the filter for names in subtitles currently only captures letters and spaces. Do you think it should capture numbers as well?

**Comment by hboetes** [comment]
Hmmm let's look at it like this

Good text contains:  One caps, lower case, other chars.
Bad text contains:    All caps, no lower case, other chars.

So... shouldn't "other chars" be an optional part of the regexp?

**Comment by mattlyon93** [comment]
The issue was that numbers weren't included in the regex to filter out the bad text for names. I've fixed this now.
