### ISSUE TITLE
more misses

### ISSUE THREAD

**Issue by hboetes** [mattlyon93/filter-subs#3]
Hello!

It's getting better, but there are still a few misses. No worries, we'll get there.
```
 00:00:07,463 --> 00:00:09,173
-FOO-BAR:
+FOO-
 I can tell you some nonsense.
 [SNIP]
- 00:00:15,846 --> 00:00:19,433
-DR. FOOBAR: We have nonsense
+DR.We have nonsense
 and gobbledygook.
```

**Comment by mattlyon93** [comment]
I'm not really sure what the filtered text should look like in this case, are you able to provide the human filtered version of what you think it should look like?

**Comment by hboetes** [comment]
I understand, and while reading it back I see the diff was a bad idea. Next time I'll simply paste a snippet that fails.
