### ISSUE TITLE
Won't delete ":" characters

### ISSUE THREAD

**Issue by seadogro** [mattlyon93/filter-subs#4]
Hi, thank you so far for your perfect tool. Unfortunately it not removes some ":" signs.

As example if you remove SDH on this sub here
https://www.opensubtitles.org/en/subtitles/8617649/s-w-a-t-sins-of-the-fathers-en

You will be left with ":" signs see picture:

and it not removes the credits and the upperscale word "TOYOTA"

Please fix if possible.
![1](https://user-images.githubusercontent.com/45518441/114063107-c6e78280-9887-11eb-9f25-78cedea32b46.PNG)
![2](https://user-images.githubusercontent.com/45518441/114063115-c949dc80-9887-11eb-8426-3958626e1650.PNG)

**Comment by mattlyon93** [comment]
Hey there,
thank you for the kind words :)

I have fixed the ':' issue, as well as the 'Captioning sponsored by' and 'Captioned by' subtitles.
Unfortunately as `subtitle-filter` parses each subtitle entry separately, I don't think it would be possible to create a rule to remove the 'and TOYOTA' line without being too restrictive on normal subtitle text.

New release version is `v1.4.1` you should be able to just `pip install --upgrade subtitle-filter`.
