### ISSUE TITLE
encoding error writing output with symbols

### ISSUE THREAD

**Issue by masteryoda34** [mattlyon93/filter-subs#5]
When using `--keep-music` option, I got the error: `UnicodeEncodeError: 'charmap' codec can't encode characters in position 35-36: character maps to <undefined>`

I was able to fix the problem by changing line 291 of `subtitle.py` from:
`with open(self._fullpath, 'w') as fp:`
to:
`with open(self._fullpath, 'w', encoding='utf-8') as fp:`

**Comment by mattlyon93** [comment]
Thanks for pointing this out.
Though I didn't get that error myself when saving some subtitles, I have still incorporated the suggested change to the latest version

Cheers
