### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by mnmll** [mattlyon93/filter-subs#7]
Hello,

The script sometimes removes the complete line. Here is an example:

Before:

`1

00:00:06,507 --> 00:00:08,467
[Moiraine] The world
is broken.

2
00:00:08,551 --> 00:00:10,302
- [voices whispering]
- Many, many years ago,

3
00:00:10,386 --> 00:00:12,555
men who were born
with great power believed`

After:

`1
00:00:08,551 --> 00:00:10,302
- Many, many years ago,

2
00:00:10,386 --> 00:00:12,555
men who were born
with great power believed`

And sometimes it's fine:

Before:

`95
00:06:57,751 --> 00:07:00,420
[Tam] I remember when this road
was just a little deer path,

96
00:07:00,504 --> 00:07:02,589
winding down the mountain.`

After:

`65
00:06:57,751 --> 00:07:00,420
I remember when this road
was just a little deer path,

66
00:07:00,504 --> 00:07:02,589
winding down the mountain.`

**Comment by mattlyon93** [comment]
Yes so the problem here is the empty newline after the `1` in the first subtitle entry:
```
1

00:00:06,507 --> 00:00:08,467
[Moiraine] The world
is broken.
```

In any case I have fixed the issue in the latest release. If you reinstall/update to version `v1.4.3`, it should be fine.

Thank you for raising this issue :+1:
